ExpenseManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from ExpenseManager import views as ExpenseManager_views
from . import views

urlpatterns = [
    path("", ExpenseManager_views.home, name="home"),
    path("admin/", admin.site.urls),
    path("first/", include("first.urls")),
    path("expense/", include("expense.urls")),
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

expense/urls.py
#from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, include
from . import views 

app_name = 'expense'

urlpatterns = [
    path('post_create/',views.post_create, name="post_create"),
    path('post_detail/<int:id>',views.post_detail, name="post_detail"),   
    path('timeline/',views.timeline, name="timeline"),
    path('post_update/<int:id>',views.post_update, name="post_update"),
    path('post_delete/<int:id>',views.post_delete, name="post_delete"),
    path('analytics/',views.analytics,name='analytics'),
    path('budget/',views.budget,name='budget'),
    path('calendar/<str:date>/<str:month>/<str:year>',views.calendar,name='calendar'),
    path('calendarToday/',views.calendarToday,name='calendarToday'),
]

first/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("expense/", include("expense.urls", namespace="expenses")),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

templates/analytics.html
{% load static %}
<!DOCTYPE html>
<html>
<title>Analytics</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'budget/css/style.css' %}">
<link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">

<body overflow="hidden" style="background-image: url('{% static 'images/analytics_img.jpg' %}'); background-size: cover;" data-aos="fade">
  <div class="parent">
		<div class="side-bar">
			<ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
        <li><a href="#categories-section" class="nav-link">Category</a></li>
        <li><a href="#month-section" class="nav-link">Monthly Balance</a></li>
        <li><a href="#year-section" class="nav-link">Annual Balance</a></li>
        <li><a href="{% url 'expense:budget' %}" class="nav-link">Budget</a></li>
        <li><a href="{% url 'expense:timeline' %}" class="nav-link">Timeline</a></li>
        <li><a href="{% url 'expense:calendarToday' %}" class="nav-link">Calendar</a></li>
				<li><a href="{% url 'home' %}" class="nav-link">Home</a></li>
      </ul>
		</div>
		
		<div class="container" overflow-y:scroll>
		<div class="page-title" ><h1><strong>Analytics</strong></h1></div>    
  <div>
    <h2 class="section-title mb-3" style="color: white; text-shadow: 2px 2px #474747;">Category-Wise Distribution</h2>  
    <div class="graph-1">
      <div class="graph-container">
      <h3 class="section-sub-title">GRAPH</h3>

        <div id="graph-chart" style="width: 75%;">
          <canvas id="donut-chart"></canvas>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <script>
          var config = {
            type: 'doughnut',
            data: {
              datasets: [{
                data: {{ data2|safe }},
                backgroundColor: [
                  '#ff2b25', '#f15a25', '#f8931f', '#ffb83c', '#ff6364'
                ],
                label: 'Category-wise Distribution'
              }],
              labels: {{ labels2|safe }}
            },
            options: {
              responsive: true
            }
          };

          window.onload = function() {
            var ctx = document.getElementById('donut-chart').getContext('2d');
            window.myPie = new Chart(ctx, config);
              var ctx1 = document.getElementById('donut-chart-annual').getContext('2d');
              window.myPie = new Chart(ctx1, config1);
      
            };

        </script>
      </div>
    </div>
  </div>

        <div id="categories-section">
        <h2 class="section-title mb-3" style="color: white; text-shadow: 2px 2px #474747;">Categories</h2>
          <div class="card-grid" style="margin-bottom: 300px;">
            {% for category in categories %}
              <div class="card">
                <div class="card-container">
                  <h4><b>{{ category.name }}</b></h4>
                  <h4>{{ category.amt }}</h4>
                  {% for subcategory in category.sub_category.all %}
                  <p>{{ subcategory.name }} : {{ subcategory.amt }}</p>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
          </div>
        </div>

        <div id="month-section" style="padding-top: 20px;">
          <h2 class="section-title mb-3" style="color: white; text-shadow: 2px 2px #474747;">Monthly Balance</h2>
          <div class="card-grid"  style="margin-bottom: 100px;">
          {% for month in months %}
            <div class="card">
              <div class="card-container">
                <h4><b>{{ month.name  }}</b></h4>
                <p>Monthly Income : {{ month.monthly_income }}</p>
                <p>Monthly Expenditure : {{ month.monthly_expenditure }}</p>
              </div>
            </div>
          {% endfor %}
          </div>    
        </div>

        <div id="year-section">
          <h2 class="section-title mb-3" style="color: white; text-shadow: 2px 2px #474747;">Annual Balance</h2>
          <div class="year">
            <div class="card-grid-year" >
            {% for year in years %}
              <div class="card">
                <div class="card-container-annual">
                  <h4><b>{{ year.name  }}</b></h4>
                  <p>Annual Income : {{ year.annual_income }}</p>
                  <p>Annual Expenditure : {{ year.annual_expenditure }}</p>
                </div>
              </div>
            {% endfor %}
            </div>    
          
          <div class="graph">
            <div class="graph-container">
            <h3 class="section-sub-title">Annual Graph</h3>
            <div id="graph-chart" style="width: 100%;">
              <canvas id="donut-chart-annual"></canvas>
            </div>
        
            <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
            <script>
              var config1 = {
                type: 'doughnut',
                data: {
                  datasets: [{
                    data: {{ data1|safe }},
                    backgroundColor: [
                      '#00a875', '#fcbf0f', '#0072bb', '#f15a23'
                    ],
                    label: 'Category-wise Distribution'
                  }],
                  labels: {{ labels1|safe }}
                },
                options: {
                  responsive: true
                }
              };
            </script>
            </div>
          </div>
        </div>

      </div>            
    </div>

  </div>


</body>
</html>

templates/base.html
{% load  staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <title>{% block head_title %}Expense Manager{% endblock head_title %}</title>

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href='{% static "/css/base.css" %}' />
    <style>
        {% block style %}{% endblock style %}
    </style>
    {% include 'base/css.html' %}
    {% include 'base/bootstrap_defaults.html' %}

</head>
<body>

    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0"></script>
    {% include "messages_display.html" %}
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>


{% block script %}
{% endblock script %}

</html>

templates/budget.html
{% load static %}
<!DOCTYPE html>
<html>
<title>Budget</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">-->
<link rel="stylesheet" href="{% static 'budget/css/style.css' %}">
<link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
<body overflow="hidden" style="background-image: url('{% static 'images/budget2_img.jpg' %}'); background-size: cover;" data-aos="fade">
	<div class="bg-image">
	<div class="parent">
		<div class="side-bar">
			<ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block" style="padding-top: 10px;">
		        <li><a href="#category-section" class="nav-link" >Category</a></li>
                <li><a href="#income-section" class="nav-link">Add Income</a></li>
                <li><a href="#create-category-section" class="nav-link">Create Category</a></li>
				<li><a href="#create-subcategory-section" class="nav-link">Create Subcategory</a></li>
				<li><a href="{% url 'expense:analytics' %}" class="nav-link">Analytics</a></li>
                <li><a href="{% url 'expense:timeline' %}" class="nav-link">Timeline</a></li>
                <li><a href="{% url 'expense:calendarToday' %}" class="nav-link">Calendar</a></li>
				<li><a href="{% url 'home' %}" class="nav-link">Home</a></li>
            </ul>
		</div>
		
		<div class="container" overflow-y:scroll >
		<div class="page-title"><h1><strong>Budget</strong></h1></div>

			<div id="category-section">
				<h2 class="section-title mb-3">Category</h2>
				<div class="card-grid" style="margin-bottom: 300px;">
				{% for category in categories %}
				<div class="card">
					<div class="card-container">
					<h4><b>{{ category.name }}</b></h4>
					<h4>Sub-Category:</h4>
					{% for subcategory in category.sub_category.all %}
					<p>{{ subcategory.name }}</p>
					{% endfor %} 
					</div>
				</div>
				{% endfor %} 
				</div>
			</div>

		
			<div id="income-section" style="padding-top: 20px;">
				<h2 class="section-title mb-3">Add Income </h2>
					<div class="card">
						<div class="single-card-container">

						<form method="POST" action=" " enctype="multipart/form-data">
						{% csrf_token %}
						{{ income_form.as_p }}
						{% if action == "create"%}
						<input type="submit" class='card-button' value="Create Income" />
						{% else %}
						<input type="update" class='card-button' value="Update Income" />
						{% endif %}
						</form>
						</div>
					</div>
			</div> 

			<div id="create-category-section">
				<h2 class="section-title mb-3">Create Category </h2>
					<div class="card">
						<div class="single-card-container">
						<form method="POST" action=" " enctype="multipart/form-data">
							{% csrf_token %}
							{{ cat_form.as_p }}
							{% if action == "create"%}
							<input type="submit" class='card-button' value="Create Category" />
							{% else %}
							<input type="update" class='card-button' value="Update Category" />
							{% endif %}
						</form>
						</div>
					</div>
			</div> 

			<div id="create-subcategory-section">
				<h2 class="section-title mb-3">Create Sub-Category </h2>
					<div class="card">
						<div class="single-card-container">
							<form method="POST" action=" " enctype="multipart/form-data">
								{% csrf_token %}
								{{ subcat_form.as_p }}
								{% if action == "create"%}
								<input type="submit" class='card-button' value="Create Sub_Category" />
								{% else %}
								<input type="update" class='card-button' value="Update Sub_Category" />
								{% endif %}
								</form>
						</div>
					</div>
			</div> 

		</div>
	</div>
</div>
</body>
</html>

templates/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendar</title>
    <link rel="stylesheet" href="{% static 'budget/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'calendar/css/calendar.css' %}" >
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

{% block csscontent %}
{% endblock csscontent %}
<!--
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
<link rel="stylesheet" href='{% static "/css/calendar.css" %}' />
-->
<body style="background-image: url('{% static 'images/calendar5_img.jpg' %}'); background-size: cover;">

{% block content %}
    <div class="float">
        <div class="blank"></div>
        <form action= "{% url 'expense:timeline' %}">
            <button class="btn btn-black btn-outline-black ml-1 rounded-0" style="padding: 20px 50px 20px 50px">Go  to Timeline</button>
        </form>
    </div>

    <div class="page">
        <div class="elegant-calendar">
            <div class="clearfix">
                <div class="head-container">
                    <div class="head-date">
                        {{date}} {{month_name}}, {{year}}
                    </div>
                    <div class="control">
                        <div class="arrows">
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="pre-next">
                                    <button name="pre"><i class="fa fa-arrow-left"></i></button>
                                    <button name="next"><i class="fa fa-arrow-right"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
        <table id="calendar" class="thead">
            <thead>
                <tr class="tableheader" style="color: #474747;">
                    <div><th {% if day_no == 0 %}class="selected" {% endif %}>Mo</th></div>
                    <div><th {% if day_no == 1 %}class="selected" {% endif %}>Tu</th></div>
                    <div><th {% if day_no == 2 %}class="selected" {% endif %}>We</th></div>
                    <div><th {% if day_no == 3 %}class="selected" {% endif %}>Th</th></div>
                    <div><th {% if day_no == 4 %}class="selected" {% endif %}>Fr</th></div>
                    <div><th {% if day_no == 5 %}class="selected" {% endif %}>Sa</th></div>
                    <div><th {% if day_no == 6 %}class="selected" {% endif %}>Su</th></div>
                </tr>
            </thead>
        <table>
        <table class="dates">
            <tbody>
                <tr class="datecolumn">
                    {% for j in gaps %}
                        <div><td></td></div>
                    {% endfor %}
                    {% for j in dates %}
                        <div>
                            <td 
                                {% if j == date %}
                                    class="selected"  
                                {% endif %}
                            >
                                <a 
                                    href="{% url 'expense:calendar' date=j month=month year=year %}"
                                >
                                    {{j}}
                                </a>
                            </td>
                        </div>
                    {% endfor %}
                </tr>   
            </tbody>
        </table>
        </div>
        <div class="dummy">
            <div class="blank"></div>
            <form action= '{% url "expense:calendarToday" %}'>
                <button class="btn btn-black mr-1 rounded-0" style="padding: 15px 15px 15px 15px">Today</button>
            </form>
        </div>
        </div>
        <div class="heading">Expenditures</div>
        <div class="days_data">
            {% if day_dataset %}
                {% for day_data in day_dataset %}
                    <div class="card">
                        <div class="single-card-container-search">
                            <div class="day_data">
                            <span class="time">{{ day_data.timestamp }}</span>  
                            <h4><b>{{ day_data.sub_category }}</b></h4>
                            <p><b>{{ day_data.spent }}</b></p>
                            </div> 
                        </div>
                    </div>
                {% endfor %} 
        </div> 
            {% else %}
            <div class="none">
                You have no Expenditures on this day.
            </div>
            {% endif %}
        </div>
        <div class="float">
            <button id="myBtn" class="add">Add Expenditure</button>
        </div>
        <div id="myModal" class="modal">
            <div class="modal-content">
    <div class="pname">Add Expenditure</div>
    <form method="POST">
    {% csrf_token %}
    <div class="row">
    <div class="key"> Date:</div>
    <input type="date" name="req_date" value="{{y}}-{{m}}-{{d}}">
    <div class="value">
    {{ form.as_p }}    
    </div>
    </div>
    <input id="reset" class="sub" type="submit" name="addexpense">
    </form>
  </div>
</div>
  {% endblock content %}


    {% block script %}
    <script>
        var modal = document.getElementById("myModal");

        var btn = document.getElementById("myBtn");


        var span = document.getElementsByClassName("close")[0];

        btn.onclick = function() {
        modal.style.display = "block";
        console.log("Sumedha");
        }

        window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
        }
</script>
  {% endblock script %}

    
</body>
</html>

templates/messages_display.html
{% if messages %}
<div class='messages'>
<ul class="messages">
{% for message in messages %}
<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message }}{% else %}{{ message }}{% endif %}</li>
{% endfor %}
</ul>
</div>
{% endif %}

templates/timeline.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<title>Timeline</title>  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'timeline1/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'timeline1/css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'timeline1/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'timeline1/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'timeline1/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'timeline1/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'timeline1/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'timeline1/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'timeline1/css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'timeline1/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'timeline1/css/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'timeline1/css/style.css' %}">

	<link href="https://fonts.googleapis.com/css?family=Dosis:300.400.700" rel="stylesheet"/>
	<link rel="stylesheet" href="{% static 'budget/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">

  </head>
  
<body overflow="hidden" style="background-image: url('{% static 'images/timeline_img.jpg' %}'); background-size: cover;" data-aos="fade">
	<div class="bg">&nbsp;</div>
	<div class="parent">
		<div class="side-bar" style="background-color: rgba(250, 252, 248, 0.67);">
			<ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block" style="padding-top: 10px;">
				<li><a href="{% url 'expense:timeline' %}" class="nav-link">All Expenditure</a></li>
				<li><a href="{% url 'expense:post_create' %}" class="nav-link">Add Expenditure</a></li>
				<li><a href="{% url 'expense:analytics' %}" class="nav-link">Analytics</a></li>
                <li><a href="{% url 'expense:budget' %}" class="nav-link">Budget</a></li>
				<li><a href="{% url 'expense:calendarToday' %}" class="nav-link">Calendar</a></li>
				<li><a href="{% url 'home' %}" class="nav-link">Home</a></li>

            </ul>
		</div>

		<div class="container" overflow-y:scroll>
		<div class="page-title"><h1><strong>TIMELINE</strong></h1></div>
		
		<div class="single-card-container-search">
			<form method="GET" action="">
				<input type="text" class='search-text'name="q" placeholder=" " value="{{ request.GET.q }}"/>
				<input type="submit" class='card-button' style="background-color: orange !important;" value="search"/>
			</form>
		</div>

		<div class id="expenditures-section">
			<h2 class="section-title mb-3" style="color: white; text-shadow: 2px 2px #474747;">Expenditures </h2>
			{% for obj in object_list %}
				<div class="card">
					<div class="single-card-container-timeline">
						<span class="time">{{ obj.timestamp|timesince }} ago</span>  
						<h4><b><a href='{{ obj.get_absolute_url }}'>{{ obj.sub_category }}</a></b></h4>
						<p><b>{{ obj.spent }}</b></p>
						<a class="btn btn-black mr-1 rounded-0" href="{{ obj.get_absolute_url }}"><b>View</b></a>
						<a class="btn btn-black mr-1 rounded-0" href="{% url 'expense:post_update' id=obj.id %}"><b>Update</b></a>
						<a class="btn btn-black mr-1 rounded-0" href="{% url 'expense:post_delete' id=obj.id %}"><b>Delete</b></a>

					</div>
				</div>
			{% endfor %}
		</div> 
		<div class="pagination">
			<span class="step-links">
				{% if object_list.has_previous %}

					<a class="btn btn-black mr-1 rounded-0" href="?{{ page_request_var }}=1"><b>First</b></a>
					<a class="btn btn-black btn-outline-black ml-1 rounded-0" href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><b>Previous</b></a>
				{% endif %}				
				{% if object_list.has_next %}
					<a class="btn btn-black mr-1 rounded-0" href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><b>Next</b></a>
					<a class="btn btn-black btn-outline-black ml-1 rounded-0" href="?{{ page_request_var }}={{ object_list.paginator.num_pages }}"><b>Last</b></a>
				{% endif %}
				<h3 class="section-sub-title-w">Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}</h3>
			</span>
		</div>
	</div>
	

</div>
  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  <script src="{% static 'timeline1/js/script.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery.min.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'timeline1/js/popper.min.js' %}"></script>
  <script src="{% static 'timeline1/js/popper.min.js' %}"></script>
  <script src="{% static 'timeline1/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'timeline1/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'timeline1/js/aos.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'timeline1/js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'timeline1/js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'timeline1/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'timeline1/js/google-map.js' %}"></script>
  <script src="{% static 'timeline1/js/main.js' %}"></script>
    
  </body>
</html>